### ISSUE TITLE
[#2] - Adds setup to connect to mongodb with mongoose

### ISSUE THREAD

**Issue by frederic-mamath** [evelyne-phich/les-bonnes-recettes-d-evy#2]
# User story

As a developer, I want to be able to persist my recipes across different computers

## Tasks

- [ ] Adds dotenv
- [ ] Adds mongoose
- [ ] Adds .env file with .env example
- [ ] Adds makefile to create an example of the required environment variables
- [ ] Adds a recipe collection
- [ ] Adds a resource to find all recipes
