### ISSUE TITLE
Complete the lesson: Static analysis testing JavaScript applications

### ISSUE THREAD

**Issue by frederic-mamath** [evelyne-phich/les-bonnes-recettes-d-evy#6]
# User story

As a developer, when I code, I want a tool to tell me what's going to be wrong or cause my application to break for any reasons

## Tasks

- [ ] Complete `Intro to Static Analysis Testing JavaScript Applications`
- [ ] Complete `Lint JavaScript by Configuring and Running ESLint`
- [ ] Complete `Use the ESLint Extension for VSCode`
- [ ] Complete `Use pre-built ESLint Configuration using extends`
- [ ] Complete `Run ESLint with npm Scripts`
- [ ] Complete `Format Code by Installing and Running Prettier`
- [ ] Complete `Configure Prettier`
- [ ] Complete `Use the Prettier Extension for VSCode`
- [ ] Complete `Disable nnecessary ESLint Stylistic Rules with eslint-config-prettier`
- [ ] Complete `Validate All Files are Properly Formatted with Prettier`
- [ ] Complete `Avoid Common Errors by Installing and Configuring TypeScript`
- [ ] Complete `Make ESLint Support TypeScript Files`
- [ ] Complete `Validate Code in a pre-commit git Hook with husky`
- [ ] Complete `Auto-format All Files and Validate Relevant Files in a precommit Script with lint-staged`
- [ ] Complete `Run mltiple npm scripts in parallel with npm-run-all`
